name: golang-pipeline

on:
  push:
    branches:
      - "*"

env:
  VERSION_TAG: "${{ github.ref_name }}-${{ github.run_number }}"
  BRANCH_TAG: "${{ vars.DOCKER_REPO }}/${{ vars.ORGANIZATION_NAME }}-${{ github.event.repository.name }}:${{ github.ref_name }}-${{ github.run_number }}"
  LATEST_TAG: "${{ vars.DOCKER_REPO }}/${{ vars.ORGANIZATION_NAME }}-${{ github.event.repository.name }}:latest"

jobs:
  test:
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: go test ./...

  deploy:
    runs-on: ubuntu-latest
    needs: test
    #if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            "${{env.BRANCH_TAG}}"
            "${{env.LATEST_TAG}}"
          build-args: |
            ${{env.VERSION_TAG}}
